### ISSUE TITLE
Anonymous sharing is broken in linshare/2.2.0

### ISSUE THREAD

**Issue by birdli66** [linagora/linshare-core#16] opened 2018-10-03 13:55 UTC
Seems that anonymous sharing needs some additional love:
`[ERROR]:http-nio-8080-exec-5:20181003.134413:org.linagora.linshare.webservice.interceptor.GenericExceptionMapper:toResponse:A NullPointerException was caught : null. 
java.lang.NullPointerException
        at org.linagora.linshare.core.notifications.dto.Share.<init>(Share.java:89)
        at org.linagora.linshare.core.notifications.emails.impl.ShareNewShareEmailBuilder.buildMailContainer(ShareNewShareEmailBuilder.java:91)
        at org.linagora.linshare.core.notifications.emails.impl.EmailBuilder.build(EmailBuilder.java:256)
        at org.linagora.linshare.core.notifications.service.impl.MailBuildingServiceImpl.build(MailBuildingServiceImpl.java:320)
        at org.linagora.linshare.core.service.impl.AnonymousShareEntryServiceImpl.create(AnonymousShareEntryServiceImpl.java:152)
        at org.linagora.linshare.core.service.impl.ShareServiceImpl.create(ShareServiceImpl.java:197)
        at org.linagora.linshare.core.facade.webservice.user.impl.ShareFacadeImpl.create(ShareFacadeImpl.java:227)
`

Seems that the expirationDate on the way from linshare_ui-user to this code get's lost.

I also had the problem, that in additional options to set an expiration date was not possible in my firefox/62.0.2 and chrome/68.0.3440.106 using the mouse (using cursor keys to move the date or writting it manually was ok), so the linshare_ui-user SPA's widget seems to not do what calendar widgets usually do.

No big deal, we currently do not intend to use the anonymous sharing.

**Comment by yazidsebahi** [comment] 2018-10-04 12:18
Hello, 
Thank you for reporting the bug.
Yes, the issue was confirmed, it will be fixed as soon as possible.

**Comment by TOFR69** [comment] 2018-10-15 09:04
Hello,
I am currently testing the linshare solution to provide a file transfer platform to users and linshare seems like an interesting solution.
I experienced the same bug on my test environment -> Blank page on Anonymous URL.
With 2.2.0-1 It is impossibile to share some files to outside users.  For me, it's a blocking point
Do you think i should downgrad the linshare version or just wait a patch for this version ?

**Comment by yazidsebahi** [comment] 2018-10-15 09:37
Hello,
Yes, you need to wait a patch for this version. 
Until the patch is out, you can enable "the expiration share" functionality in administration interface to solve this problem.

**Comment by TOFR69** [comment] 2018-10-15 10:05
Thank you for your quick reply.
After checking, it seems that the problem is not exactly the same because the anonymous URL does not work (blank page) even if the "the expiration share" functionality is enabled.
More over in Tomcat log, I can see a code ANONYMOUS_URL_FORBIDDEN which leaves me thought about a problem of authorization ...
Do you already have experiment this error ?

859:org.linagora.linshare.core.service.AnonymousUrlService:accessBusinessCheck:Checking access 
[ERROR]:http-nio-8080-exec-5:20181015.094859:org.linagora.linshare.webservice.interceptor.BusinessExceptionMapper:toResponse:A BusinessException was caught : code=ANONYMOUS_URL_FORBIDDEN,  You do not have the right to get this anonymous url : 4726335e-730b-4d8f-9b9e-a8d046a7e140
[DEBUG]:http-nio-8080-exec-5:20181015.094859:org.linagora.linshare.webservice.interceptor.BusinessExceptionMapper:toResponse:Stacktrace: 
org.linagora.linshare.core.exception.BusinessException: You do not have the right to get this anonymous url : 4726335e-730b-4d8f-9b9e-a8d046a7e140

**Comment by yazidsebahi** [comment] 2018-10-15 13:33
Hello,
Yes I confirme this bug for 2.2.0-1.
You can downgrade the LinShare version to 2.1.x to use this feature.

**Comment by yazidsebahi** [comment] 2018-11-06 08:59
Hello,
LinShare 2.2.1 release is out, with fixing the Anonymous sharing and Anonymous URL.
You can find [here](https://github.com/linagora/linshare/blob/master/CHANGELOG.md) the changelog of this release.

**Closed** 2018-11-06 13:40 UTC
